target("nng_test")
    set_kind("binary")
    add_includedirs("$(nng_sdk)/include","$(projectdir)/../nng/src")
    add_linkdirs("$(nng_sdk)/lib")
    add_links("nng")
    add_syslinks("pthread", "m", "rt", "dl")
    add_files("httpserver.c", "convey.c")

target("convey_test")
    set_kind("binary")
    add_includedirs("$(nng_sdk)/include","$(projectdir)/convey")
    add_linkdirs("$(nng_sdk)/lib")
    add_links("nng")
    add_syslinks("pthread", "m", "rt", "dl")
    add_files("convey_test.c", "$(projectdir)/convey/convey.c")
